# Generated by Django 3.0.2 on 2020-01-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
