# Generated by Django 3.0.2 on 2020-01-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_apikeys_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='api_key',
            field=models.IntegerField(default=0),
        ),
    ]
